name = "HaloMF"
uuid = "0e139a23-195b-4aec-b8fc-e9aa4361bc8d"
authors = ["Eiichiro Komatsu <eiichirokomatsu@me.com>"]
version = "0.1.0"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
